project:
  type: website
  output-dir: docs
  
website:
  title: "ESS 411 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Lecture Slides
      - href: readings.qmd
        text: Readings
      - href: assignments.qmd
        text: Assignments
      - href: weekly_reflections.qmd
        text: Weekly Reflections
      - href: course_reflection.qmd
        text: Course Reflection
        
resources: 
  - "slides/*.pdf"
  - "readings/*.pdf"
  - "assignments/*.pdf"

format:
  html:
    theme: styles.scss
    toc: true

editor: visual

