project:
  type: website
  output-dir: docs
  
website:
  title: "ESS 411 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Lecture Slides
      - href: readings.qmd
        text: Readings
      - href: assignments.qmd
        text: Assignments
        
resources: 
  - "slides/*.pdf"
  - "readings/*.pdf"
  - "assignments/*.pdf"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

