project:
  type: website
  output-dir: docs
  
website:
  title: "ESS 411 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides.qmd
        text: Lecture Slides

resources: 
  - "slides/*.pdf"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

